Conditions on static ldd check

diff --git a/.github/workflows/build-manylinux.yml b/.github/workflows/build-manylinux.yml
--- a/.github/workflows/build-manylinux.yml
+++ b/.github/workflows/build-manylinux.yml
@@ -63,7 +63,11 @@ jobs:
           cd Cell2Fire
           make clean
           make -f makefile.static > ldd_manylinux.txt  2>&1|| true
-          ! ldd Cell2Fire
+          if ! ldd Cell2Fire; then
+            echo "Command failed"
+            else
+            echo "Command succeeded"
+          fi
 
       - name: Upload Static
         uses: actions/upload-artifact@v4
